spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/usuarios
        username: postgres
        password: root
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

        hibernate:
            ddl-auto: update
    security:
        user:
            name: user
            password: aae9ed18-353b-4022-93ba-f423cbe17256
    
